name: user_post
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

lobal_options:
  freezed:freezed:
    runs_before:
      - isar_generator:isar_generator

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  either_dart: ^0.4.0
  dio: ^5.1.2
  flutter_riverpod: ^2.3.6
  isar: ^3.1.0+1
  path_provider: ^2.0.15
  isar_flutter_libs: ^3.1.0+1
  go_router: ^7.1.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
